version: '3'
services:
  version-check:
    image: katanas/version-check:v0.5.1
    env_file:
      - .env
    depends_on:
      - etcd1

  etcd1:
    image: quay.io/coreos/etcd:v3.1.7
    restart: always
    ports:
      - 23791:2379
      - 23801:2380
    volumes:
      - etcd1:/etcd_data
    environment:
      ETCD_NAME: infra1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
      ETCD_INITIAL_CLUSTER: infra1=http://etcd1:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-testing-01
      ETCD_LISTEN_CLIENT_URLS: http://etcd1:2379,http://localhost:2379
      ETCD_LISTEN_PEER_URLS: http://etcd1:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379

volumes:
  etcd1:
